sudo: false
language: python

install: 
    - pip install tox

script:
    - tox

notifications:
    on_success: change
    on_failure: allways

matrix:
    include:
        - python: 3.5
          env: TOXENV=flake8
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=docs
